org: vitorsoaresp
app: aws-node-rest-api
service: aws-node-rest-api

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    NODE_ENV: dev
  httpApi:
    cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  exclude:
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  # create:
  #   handler: app/handler.create
  #   events:
  #     - http:
  #         path: employees
  #         method: post
  find:
    handler: app/handler.find
    events:
      - http:
          path: employees
          method: get
          cors: true
  headcount:
    handler: app/handler.headcount
    events:
      - http:
          path: employees/headcount/{manager}
          cors: true
          method: get
  turnover:
    handler: app/handler.turnover
    events:
      - http:
          path: employees/turnover/{manager}
          cors: true
          method: get
  login:
    handler: app/handler.login
    events:
      - http:
          path: login
          cors: true
          method: post
